/**
 * SPDX-FileCopyrightText: (c) 2023 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.permission.template.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.permission.template.model.PermissionTemplate;
import com.liferay.permission.template.model.PermissionTemplateModel;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portal.kernel.util.Validator;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the PermissionTemplate service. Represents a row in the &quot;PermissionTemplate&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>PermissionTemplateModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PermissionTemplateImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PermissionTemplateImpl
 * @generated
 */
public class PermissionTemplateModelImpl
	extends BaseModelImpl<PermissionTemplate>
	implements PermissionTemplateModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a permission template model instance should use the <code>PermissionTemplate</code> interface instead.
	 */
	public static final String TABLE_NAME = "PermissionTemplate";

	public static final Object[][] TABLE_COLUMNS = {
		{"mvccVersion", Types.BIGINT}, {"ctCollectionId", Types.BIGINT},
		{"permissionTemplateId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"classNameId", Types.BIGINT},
		{"classPK", Types.BIGINT}, {"permissionTemplateEnabled", Types.BOOLEAN}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("mvccVersion", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("ctCollectionId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("permissionTemplateId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("classNameId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("classPK", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("permissionTemplateEnabled", Types.BOOLEAN);
	}

	public static final String TABLE_SQL_CREATE =
		"create table PermissionTemplate (mvccVersion LONG default 0 not null,ctCollectionId LONG default 0 not null,permissionTemplateId LONG not null,groupId LONG,companyId LONG,classNameId LONG,classPK LONG,permissionTemplateEnabled BOOLEAN,primary key (permissionTemplateId, ctCollectionId))";

	public static final String TABLE_SQL_DROP = "drop table PermissionTemplate";

	public static final String ORDER_BY_JPQL =
		" ORDER BY permissionTemplate.permissionTemplateId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY PermissionTemplate.permissionTemplateId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PERMISSIONTEMPLATEID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public PermissionTemplateModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _permissionTemplateId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setPermissionTemplateId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _permissionTemplateId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return PermissionTemplate.class;
	}

	@Override
	public String getModelClassName() {
		return PermissionTemplate.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<PermissionTemplate, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<PermissionTemplate, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<PermissionTemplate, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((PermissionTemplate)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<PermissionTemplate, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<PermissionTemplate, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(PermissionTemplate)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<PermissionTemplate, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<PermissionTemplate, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<PermissionTemplate, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<PermissionTemplate, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<PermissionTemplate, Object>>();

			attributeGetterFunctions.put(
				"mvccVersion", PermissionTemplate::getMvccVersion);
			attributeGetterFunctions.put(
				"ctCollectionId", PermissionTemplate::getCtCollectionId);
			attributeGetterFunctions.put(
				"permissionTemplateId",
				PermissionTemplate::getPermissionTemplateId);
			attributeGetterFunctions.put(
				"groupId", PermissionTemplate::getGroupId);
			attributeGetterFunctions.put(
				"companyId", PermissionTemplate::getCompanyId);
			attributeGetterFunctions.put(
				"classNameId", PermissionTemplate::getClassNameId);
			attributeGetterFunctions.put(
				"classPK", PermissionTemplate::getClassPK);
			attributeGetterFunctions.put(
				"permissionTemplateEnabled",
				PermissionTemplate::getPermissionTemplateEnabled);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<PermissionTemplate, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<PermissionTemplate, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap
						<String, BiConsumer<PermissionTemplate, ?>>();

			attributeSetterBiConsumers.put(
				"mvccVersion",
				(BiConsumer<PermissionTemplate, Long>)
					PermissionTemplate::setMvccVersion);
			attributeSetterBiConsumers.put(
				"ctCollectionId",
				(BiConsumer<PermissionTemplate, Long>)
					PermissionTemplate::setCtCollectionId);
			attributeSetterBiConsumers.put(
				"permissionTemplateId",
				(BiConsumer<PermissionTemplate, Long>)
					PermissionTemplate::setPermissionTemplateId);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<PermissionTemplate, Long>)
					PermissionTemplate::setGroupId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<PermissionTemplate, Long>)
					PermissionTemplate::setCompanyId);
			attributeSetterBiConsumers.put(
				"classNameId",
				(BiConsumer<PermissionTemplate, Long>)
					PermissionTemplate::setClassNameId);
			attributeSetterBiConsumers.put(
				"classPK",
				(BiConsumer<PermissionTemplate, Long>)
					PermissionTemplate::setClassPK);
			attributeSetterBiConsumers.put(
				"permissionTemplateEnabled",
				(BiConsumer<PermissionTemplate, Boolean>)
					PermissionTemplate::setPermissionTemplateEnabled);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@Override
	public long getMvccVersion() {
		return _mvccVersion;
	}

	@Override
	public void setMvccVersion(long mvccVersion) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_mvccVersion = mvccVersion;
	}

	@Override
	public long getCtCollectionId() {
		return _ctCollectionId;
	}

	@Override
	public void setCtCollectionId(long ctCollectionId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ctCollectionId = ctCollectionId;
	}

	@Override
	public long getPermissionTemplateId() {
		return _permissionTemplateId;
	}

	@Override
	public void setPermissionTemplateId(long permissionTemplateId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_permissionTemplateId = permissionTemplateId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@Override
	public String getClassName() {
		if (getClassNameId() <= 0) {
			return "";
		}

		return PortalUtil.getClassName(getClassNameId());
	}

	@Override
	public void setClassName(String className) {
		long classNameId = 0;

		if (Validator.isNotNull(className)) {
			classNameId = PortalUtil.getClassNameId(className);
		}

		setClassNameId(classNameId);
	}

	@Override
	public long getClassNameId() {
		return _classNameId;
	}

	@Override
	public void setClassNameId(long classNameId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_classNameId = classNameId;
	}

	@Override
	public long getClassPK() {
		return _classPK;
	}

	@Override
	public void setClassPK(long classPK) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_classPK = classPK;
	}

	@Override
	public boolean getPermissionTemplateEnabled() {
		return _permissionTemplateEnabled;
	}

	@Override
	public boolean isPermissionTemplateEnabled() {
		return _permissionTemplateEnabled;
	}

	@Override
	public void setPermissionTemplateEnabled(
		boolean permissionTemplateEnabled) {

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_permissionTemplateEnabled = permissionTemplateEnabled;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), PermissionTemplate.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public PermissionTemplate toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, PermissionTemplate>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		PermissionTemplateImpl permissionTemplateImpl =
			new PermissionTemplateImpl();

		permissionTemplateImpl.setMvccVersion(getMvccVersion());
		permissionTemplateImpl.setCtCollectionId(getCtCollectionId());
		permissionTemplateImpl.setPermissionTemplateId(
			getPermissionTemplateId());
		permissionTemplateImpl.setGroupId(getGroupId());
		permissionTemplateImpl.setCompanyId(getCompanyId());
		permissionTemplateImpl.setClassNameId(getClassNameId());
		permissionTemplateImpl.setClassPK(getClassPK());
		permissionTemplateImpl.setPermissionTemplateEnabled(
			isPermissionTemplateEnabled());

		permissionTemplateImpl.resetOriginalValues();

		return permissionTemplateImpl;
	}

	@Override
	public PermissionTemplate cloneWithOriginalValues() {
		PermissionTemplateImpl permissionTemplateImpl =
			new PermissionTemplateImpl();

		permissionTemplateImpl.setMvccVersion(
			this.<Long>getColumnOriginalValue("mvccVersion"));
		permissionTemplateImpl.setCtCollectionId(
			this.<Long>getColumnOriginalValue("ctCollectionId"));
		permissionTemplateImpl.setPermissionTemplateId(
			this.<Long>getColumnOriginalValue("permissionTemplateId"));
		permissionTemplateImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		permissionTemplateImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		permissionTemplateImpl.setClassNameId(
			this.<Long>getColumnOriginalValue("classNameId"));
		permissionTemplateImpl.setClassPK(
			this.<Long>getColumnOriginalValue("classPK"));
		permissionTemplateImpl.setPermissionTemplateEnabled(
			this.<Boolean>getColumnOriginalValue("permissionTemplateEnabled"));

		return permissionTemplateImpl;
	}

	@Override
	public int compareTo(PermissionTemplate permissionTemplate) {
		long primaryKey = permissionTemplate.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof PermissionTemplate)) {
			return false;
		}

		PermissionTemplate permissionTemplate = (PermissionTemplate)object;

		long primaryKey = permissionTemplate.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<PermissionTemplate> toCacheModel() {
		PermissionTemplateCacheModel permissionTemplateCacheModel =
			new PermissionTemplateCacheModel();

		permissionTemplateCacheModel.mvccVersion = getMvccVersion();

		permissionTemplateCacheModel.ctCollectionId = getCtCollectionId();

		permissionTemplateCacheModel.permissionTemplateId =
			getPermissionTemplateId();

		permissionTemplateCacheModel.groupId = getGroupId();

		permissionTemplateCacheModel.companyId = getCompanyId();

		permissionTemplateCacheModel.classNameId = getClassNameId();

		permissionTemplateCacheModel.classPK = getClassPK();

		permissionTemplateCacheModel.permissionTemplateEnabled =
			isPermissionTemplateEnabled();

		return permissionTemplateCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<PermissionTemplate, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<PermissionTemplate, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<PermissionTemplate, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(PermissionTemplate)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, PermissionTemplate>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					PermissionTemplate.class, ModelWrapper.class);

	}

	private long _mvccVersion;
	private long _ctCollectionId;
	private long _permissionTemplateId;
	private long _groupId;
	private long _companyId;
	private long _classNameId;
	private long _classPK;
	private boolean _permissionTemplateEnabled;

	public <T> T getColumnValue(String columnName) {
		Function<PermissionTemplate, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((PermissionTemplate)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("mvccVersion", _mvccVersion);
		_columnOriginalValues.put("ctCollectionId", _ctCollectionId);
		_columnOriginalValues.put(
			"permissionTemplateId", _permissionTemplateId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("classNameId", _classNameId);
		_columnOriginalValues.put("classPK", _classPK);
		_columnOriginalValues.put(
			"permissionTemplateEnabled", _permissionTemplateEnabled);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("mvccVersion", 1L);

		columnBitmasks.put("ctCollectionId", 2L);

		columnBitmasks.put("permissionTemplateId", 4L);

		columnBitmasks.put("groupId", 8L);

		columnBitmasks.put("companyId", 16L);

		columnBitmasks.put("classNameId", 32L);

		columnBitmasks.put("classPK", 64L);

		columnBitmasks.put("permissionTemplateEnabled", 128L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private PermissionTemplate _escapedModel;

}