/**
 * SPDX-FileCopyrightText: (c) 2023 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.permission.template.model.impl;

import com.liferay.permission.template.model.PermissionTemplate;
import com.liferay.permission.template.service.PermissionTemplateLocalServiceUtil;

/**
 * The extended model base implementation for the PermissionTemplate service. Represents a row in the &quot;PermissionTemplate&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PermissionTemplateImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PermissionTemplateImpl
 * @see PermissionTemplate
 * @generated
 */
public abstract class PermissionTemplateBaseImpl
	extends PermissionTemplateModelImpl implements PermissionTemplate {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a permission template model instance should use the <code>PermissionTemplate</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			PermissionTemplateLocalServiceUtil.addPermissionTemplate(this);
		}
		else {
			PermissionTemplateLocalServiceUtil.updatePermissionTemplate(this);
		}
	}

}