/**
 * SPDX-FileCopyrightText: (c) 2023 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.portal.model.impl;

import com.liferay.portal.kernel.model.PermissionPropagationEntry;
import com.liferay.portal.kernel.service.PermissionPropagationEntryLocalServiceUtil;

/**
 * The extended model base implementation for the PermissionPropagationEntry service. Represents a row in the &quot;PermissionPropagationEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PermissionPropagationEntryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PermissionPropagationEntryImpl
 * @see PermissionPropagationEntry
 * @generated
 */
public abstract class PermissionPropagationEntryBaseImpl
	extends PermissionPropagationEntryModelImpl
	implements PermissionPropagationEntry {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a permission propagation entry model instance should use the <code>PermissionPropagationEntry</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			PermissionPropagationEntryLocalServiceUtil.
				addPermissionPropagationEntry(this);
		}
		else {
			PermissionPropagationEntryLocalServiceUtil.
				updatePermissionPropagationEntry(this);
		}
	}

}