/**
 * SPDX-FileCopyrightText: (c) 2023 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.portal.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.PermissionPropagationEntry;
import com.liferay.portal.kernel.model.PermissionPropagationEntryModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portal.kernel.util.Validator;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the PermissionPropagationEntry service. Represents a row in the &quot;PermissionPropagationEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>PermissionPropagationEntryModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PermissionPropagationEntryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PermissionPropagationEntryImpl
 * @generated
 */
public class PermissionPropagationEntryModelImpl
	extends BaseModelImpl<PermissionPropagationEntry>
	implements PermissionPropagationEntryModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a permission propagation entry model instance should use the <code>PermissionPropagationEntry</code> interface instead.
	 */
	public static final String TABLE_NAME = "PermissionPropagationEntry";

	public static final Object[][] TABLE_COLUMNS = {
		{"mvccVersion", Types.BIGINT}, {"ctCollectionId", Types.BIGINT},
		{"permissionPropagationEntryId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"classNameId", Types.BIGINT}, {"classPK", Types.BIGINT},
		{"propagation", Types.BOOLEAN}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("mvccVersion", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("ctCollectionId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("permissionPropagationEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("classNameId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("classPK", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("propagation", Types.BOOLEAN);
	}

	public static final String TABLE_SQL_CREATE =
		"create table PermissionPropagationEntry (mvccVersion LONG default 0 not null,ctCollectionId LONG default 0 not null,permissionPropagationEntryId LONG not null,groupId LONG,companyId LONG,classNameId LONG,classPK LONG,propagation BOOLEAN,primary key (permissionPropagationEntryId, ctCollectionId))";

	public static final String TABLE_SQL_DROP =
		"drop table PermissionPropagationEntry";

	public static final String ORDER_BY_JPQL =
		" ORDER BY permissionPropagationEntry.permissionPropagationEntryId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY PermissionPropagationEntry.permissionPropagationEntryId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean ENTITY_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean FINDER_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean COLUMN_BITMASK_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PERMISSIONPROPAGATIONENTRYID_COLUMN_BITMASK = 1L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.liferay.portal.util.PropsUtil.get(
			"lock.expiration.time.com.liferay.portal.kernel.model.PermissionPropagationEntry"));

	public PermissionPropagationEntryModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _permissionPropagationEntryId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setPermissionPropagationEntryId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _permissionPropagationEntryId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return PermissionPropagationEntry.class;
	}

	@Override
	public String getModelClassName() {
		return PermissionPropagationEntry.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<PermissionPropagationEntry, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<PermissionPropagationEntry, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<PermissionPropagationEntry, Object>
				attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply(
					(PermissionPropagationEntry)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<PermissionPropagationEntry, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<PermissionPropagationEntry, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(PermissionPropagationEntry)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<PermissionPropagationEntry, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<PermissionPropagationEntry, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map
			<String, Function<PermissionPropagationEntry, Object>>
				_attributeGetterFunctions;

		static {
			Map<String, Function<PermissionPropagationEntry, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String,
						 Function<PermissionPropagationEntry, Object>>();

			attributeGetterFunctions.put(
				"mvccVersion", PermissionPropagationEntry::getMvccVersion);
			attributeGetterFunctions.put(
				"ctCollectionId",
				PermissionPropagationEntry::getCtCollectionId);
			attributeGetterFunctions.put(
				"permissionPropagationEntryId",
				PermissionPropagationEntry::getPermissionPropagationEntryId);
			attributeGetterFunctions.put(
				"groupId", PermissionPropagationEntry::getGroupId);
			attributeGetterFunctions.put(
				"companyId", PermissionPropagationEntry::getCompanyId);
			attributeGetterFunctions.put(
				"classNameId", PermissionPropagationEntry::getClassNameId);
			attributeGetterFunctions.put(
				"classPK", PermissionPropagationEntry::getClassPK);
			attributeGetterFunctions.put(
				"propagation", PermissionPropagationEntry::getPropagation);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map
			<String, BiConsumer<PermissionPropagationEntry, Object>>
				_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<PermissionPropagationEntry, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap
						<String, BiConsumer<PermissionPropagationEntry, ?>>();

			attributeSetterBiConsumers.put(
				"mvccVersion",
				(BiConsumer<PermissionPropagationEntry, Long>)
					PermissionPropagationEntry::setMvccVersion);
			attributeSetterBiConsumers.put(
				"ctCollectionId",
				(BiConsumer<PermissionPropagationEntry, Long>)
					PermissionPropagationEntry::setCtCollectionId);
			attributeSetterBiConsumers.put(
				"permissionPropagationEntryId",
				(BiConsumer<PermissionPropagationEntry, Long>)
					PermissionPropagationEntry::
						setPermissionPropagationEntryId);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<PermissionPropagationEntry, Long>)
					PermissionPropagationEntry::setGroupId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<PermissionPropagationEntry, Long>)
					PermissionPropagationEntry::setCompanyId);
			attributeSetterBiConsumers.put(
				"classNameId",
				(BiConsumer<PermissionPropagationEntry, Long>)
					PermissionPropagationEntry::setClassNameId);
			attributeSetterBiConsumers.put(
				"classPK",
				(BiConsumer<PermissionPropagationEntry, Long>)
					PermissionPropagationEntry::setClassPK);
			attributeSetterBiConsumers.put(
				"propagation",
				(BiConsumer<PermissionPropagationEntry, Boolean>)
					PermissionPropagationEntry::setPropagation);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@Override
	public long getMvccVersion() {
		return _mvccVersion;
	}

	@Override
	public void setMvccVersion(long mvccVersion) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_mvccVersion = mvccVersion;
	}

	@Override
	public long getCtCollectionId() {
		return _ctCollectionId;
	}

	@Override
	public void setCtCollectionId(long ctCollectionId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ctCollectionId = ctCollectionId;
	}

	@Override
	public long getPermissionPropagationEntryId() {
		return _permissionPropagationEntryId;
	}

	@Override
	public void setPermissionPropagationEntryId(
		long permissionPropagationEntryId) {

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_permissionPropagationEntryId = permissionPropagationEntryId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@Override
	public String getClassName() {
		if (getClassNameId() <= 0) {
			return "";
		}

		return PortalUtil.getClassName(getClassNameId());
	}

	@Override
	public void setClassName(String className) {
		long classNameId = 0;

		if (Validator.isNotNull(className)) {
			classNameId = PortalUtil.getClassNameId(className);
		}

		setClassNameId(classNameId);
	}

	@Override
	public long getClassNameId() {
		return _classNameId;
	}

	@Override
	public void setClassNameId(long classNameId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_classNameId = classNameId;
	}

	@Override
	public long getClassPK() {
		return _classPK;
	}

	@Override
	public void setClassPK(long classPK) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_classPK = classPK;
	}

	@Override
	public boolean getPropagation() {
		return _propagation;
	}

	@Override
	public boolean isPropagation() {
		return _propagation;
	}

	@Override
	public void setPropagation(boolean propagation) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_propagation = propagation;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), PermissionPropagationEntry.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public PermissionPropagationEntry toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, PermissionPropagationEntry>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		PermissionPropagationEntryImpl permissionPropagationEntryImpl =
			new PermissionPropagationEntryImpl();

		permissionPropagationEntryImpl.setMvccVersion(getMvccVersion());
		permissionPropagationEntryImpl.setCtCollectionId(getCtCollectionId());
		permissionPropagationEntryImpl.setPermissionPropagationEntryId(
			getPermissionPropagationEntryId());
		permissionPropagationEntryImpl.setGroupId(getGroupId());
		permissionPropagationEntryImpl.setCompanyId(getCompanyId());
		permissionPropagationEntryImpl.setClassNameId(getClassNameId());
		permissionPropagationEntryImpl.setClassPK(getClassPK());
		permissionPropagationEntryImpl.setPropagation(isPropagation());

		permissionPropagationEntryImpl.resetOriginalValues();

		return permissionPropagationEntryImpl;
	}

	@Override
	public PermissionPropagationEntry cloneWithOriginalValues() {
		PermissionPropagationEntryImpl permissionPropagationEntryImpl =
			new PermissionPropagationEntryImpl();

		permissionPropagationEntryImpl.setMvccVersion(
			this.<Long>getColumnOriginalValue("mvccVersion"));
		permissionPropagationEntryImpl.setCtCollectionId(
			this.<Long>getColumnOriginalValue("ctCollectionId"));
		permissionPropagationEntryImpl.setPermissionPropagationEntryId(
			this.<Long>getColumnOriginalValue("permissionPropagationEntryId"));
		permissionPropagationEntryImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		permissionPropagationEntryImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		permissionPropagationEntryImpl.setClassNameId(
			this.<Long>getColumnOriginalValue("classNameId"));
		permissionPropagationEntryImpl.setClassPK(
			this.<Long>getColumnOriginalValue("classPK"));
		permissionPropagationEntryImpl.setPropagation(
			this.<Boolean>getColumnOriginalValue("propagation"));

		return permissionPropagationEntryImpl;
	}

	@Override
	public int compareTo(
		PermissionPropagationEntry permissionPropagationEntry) {

		long primaryKey = permissionPropagationEntry.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof PermissionPropagationEntry)) {
			return false;
		}

		PermissionPropagationEntry permissionPropagationEntry =
			(PermissionPropagationEntry)object;

		long primaryKey = permissionPropagationEntry.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<PermissionPropagationEntry> toCacheModel() {
		PermissionPropagationEntryCacheModel
			permissionPropagationEntryCacheModel =
				new PermissionPropagationEntryCacheModel();

		permissionPropagationEntryCacheModel.mvccVersion = getMvccVersion();

		permissionPropagationEntryCacheModel.ctCollectionId =
			getCtCollectionId();

		permissionPropagationEntryCacheModel.permissionPropagationEntryId =
			getPermissionPropagationEntryId();

		permissionPropagationEntryCacheModel.groupId = getGroupId();

		permissionPropagationEntryCacheModel.companyId = getCompanyId();

		permissionPropagationEntryCacheModel.classNameId = getClassNameId();

		permissionPropagationEntryCacheModel.classPK = getClassPK();

		permissionPropagationEntryCacheModel.propagation = isPropagation();

		return permissionPropagationEntryCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<PermissionPropagationEntry, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<PermissionPropagationEntry, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<PermissionPropagationEntry, Object>
				attributeGetterFunction = entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(PermissionPropagationEntry)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function
			<InvocationHandler, PermissionPropagationEntry>
				_escapedModelProxyProviderFunction =
					ProxyUtil.getProxyProviderFunction(
						PermissionPropagationEntry.class, ModelWrapper.class);

	}

	private long _mvccVersion;
	private long _ctCollectionId;
	private long _permissionPropagationEntryId;
	private long _groupId;
	private long _companyId;
	private long _classNameId;
	private long _classPK;
	private boolean _propagation;

	public <T> T getColumnValue(String columnName) {
		Function<PermissionPropagationEntry, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((PermissionPropagationEntry)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("mvccVersion", _mvccVersion);
		_columnOriginalValues.put("ctCollectionId", _ctCollectionId);
		_columnOriginalValues.put(
			"permissionPropagationEntryId", _permissionPropagationEntryId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("classNameId", _classNameId);
		_columnOriginalValues.put("classPK", _classPK);
		_columnOriginalValues.put("propagation", _propagation);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("mvccVersion", 1L);

		columnBitmasks.put("ctCollectionId", 2L);

		columnBitmasks.put("permissionPropagationEntryId", 4L);

		columnBitmasks.put("groupId", 8L);

		columnBitmasks.put("companyId", 16L);

		columnBitmasks.put("classNameId", 32L);

		columnBitmasks.put("classPK", 64L);

		columnBitmasks.put("propagation", 128L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private PermissionPropagationEntry _escapedModel;

}