/**
 * SPDX-FileCopyrightText: (c) 2023 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.permission.template.service.base;

import com.liferay.permission.template.model.PermissionTemplateSetting;
import com.liferay.permission.template.service.PermissionTemplateSettingLocalService;
import com.liferay.permission.template.service.PermissionTemplateSettingLocalServiceUtil;
import com.liferay.permission.template.service.persistence.PermissionTemplateSettingPersistence;
import com.liferay.petra.function.UnsafeFunction;
import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.change.tracking.CTService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.service.persistence.change.tracking.CTPersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the permission template setting local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.permission.template.service.impl.PermissionTemplateSettingLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.liferay.permission.template.service.impl.PermissionTemplateSettingLocalServiceImpl
 * @generated
 */
public abstract class PermissionTemplateSettingLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, IdentifiableOSGiService,
			   PermissionTemplateSettingLocalService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>PermissionTemplateSettingLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>PermissionTemplateSettingLocalServiceUtil</code>.
	 */

	/**
	 * Adds the permission template setting to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect PermissionTemplateSettingLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param permissionTemplateSetting the permission template setting
	 * @return the permission template setting that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public PermissionTemplateSetting addPermissionTemplateSetting(
		PermissionTemplateSetting permissionTemplateSetting) {

		permissionTemplateSetting.setNew(true);

		return permissionTemplateSettingPersistence.update(
			permissionTemplateSetting);
	}

	/**
	 * Creates a new permission template setting with the primary key. Does not add the permission template setting to the database.
	 *
	 * @param permissionTemplateSettingId the primary key for the new permission template setting
	 * @return the new permission template setting
	 */
	@Override
	@Transactional(enabled = false)
	public PermissionTemplateSetting createPermissionTemplateSetting(
		long permissionTemplateSettingId) {

		return permissionTemplateSettingPersistence.create(
			permissionTemplateSettingId);
	}

	/**
	 * Deletes the permission template setting with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect PermissionTemplateSettingLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param permissionTemplateSettingId the primary key of the permission template setting
	 * @return the permission template setting that was removed
	 * @throws PortalException if a permission template setting with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public PermissionTemplateSetting deletePermissionTemplateSetting(
			long permissionTemplateSettingId)
		throws PortalException {

		return permissionTemplateSettingPersistence.remove(
			permissionTemplateSettingId);
	}

	/**
	 * Deletes the permission template setting from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect PermissionTemplateSettingLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param permissionTemplateSetting the permission template setting
	 * @return the permission template setting that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public PermissionTemplateSetting deletePermissionTemplateSetting(
		PermissionTemplateSetting permissionTemplateSetting) {

		return permissionTemplateSettingPersistence.remove(
			permissionTemplateSetting);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return permissionTemplateSettingPersistence.dslQuery(dslQuery);
	}

	@Override
	public int dslQueryCount(DSLQuery dslQuery) {
		Long count = dslQuery(dslQuery);

		return count.intValue();
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			PermissionTemplateSetting.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return permissionTemplateSettingPersistence.findWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.permission.template.model.impl.PermissionTemplateSettingModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return permissionTemplateSettingPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.permission.template.model.impl.PermissionTemplateSettingModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return permissionTemplateSettingPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return permissionTemplateSettingPersistence.countWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return permissionTemplateSettingPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public PermissionTemplateSetting fetchPermissionTemplateSetting(
		long permissionTemplateSettingId) {

		return permissionTemplateSettingPersistence.fetchByPrimaryKey(
			permissionTemplateSettingId);
	}

	/**
	 * Returns the permission template setting with the primary key.
	 *
	 * @param permissionTemplateSettingId the primary key of the permission template setting
	 * @return the permission template setting
	 * @throws PortalException if a permission template setting with the primary key could not be found
	 */
	@Override
	public PermissionTemplateSetting getPermissionTemplateSetting(
			long permissionTemplateSettingId)
		throws PortalException {

		return permissionTemplateSettingPersistence.findByPrimaryKey(
			permissionTemplateSettingId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(
			permissionTemplateSettingLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(PermissionTemplateSetting.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"permissionTemplateSettingId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			permissionTemplateSettingLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(
			PermissionTemplateSetting.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"permissionTemplateSettingId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(
			permissionTemplateSettingLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(PermissionTemplateSetting.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"permissionTemplateSettingId");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return permissionTemplateSettingPersistence.create(
			((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		if (_log.isWarnEnabled()) {
			_log.warn(
				"Implement PermissionTemplateSettingLocalServiceImpl#deletePermissionTemplateSetting(PermissionTemplateSetting) to avoid orphaned data");
		}

		return permissionTemplateSettingLocalService.
			deletePermissionTemplateSetting(
				(PermissionTemplateSetting)persistedModel);
	}

	@Override
	public BasePersistence<PermissionTemplateSetting> getBasePersistence() {
		return permissionTemplateSettingPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return permissionTemplateSettingPersistence.findByPrimaryKey(
			primaryKeyObj);
	}

	/**
	 * Returns a range of all the permission template settings.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.permission.template.model.impl.PermissionTemplateSettingModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of permission template settings
	 * @param end the upper bound of the range of permission template settings (not inclusive)
	 * @return the range of permission template settings
	 */
	@Override
	public List<PermissionTemplateSetting> getPermissionTemplateSettings(
		int start, int end) {

		return permissionTemplateSettingPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of permission template settings.
	 *
	 * @return the number of permission template settings
	 */
	@Override
	public int getPermissionTemplateSettingsCount() {
		return permissionTemplateSettingPersistence.countAll();
	}

	/**
	 * Updates the permission template setting in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect PermissionTemplateSettingLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param permissionTemplateSetting the permission template setting
	 * @return the permission template setting that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public PermissionTemplateSetting updatePermissionTemplateSetting(
		PermissionTemplateSetting permissionTemplateSetting) {

		return permissionTemplateSettingPersistence.update(
			permissionTemplateSetting);
	}

	@Deactivate
	protected void deactivate() {
		PermissionTemplateSettingLocalServiceUtil.setService(null);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			PermissionTemplateSettingLocalService.class,
			IdentifiableOSGiService.class, CTService.class,
			PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		permissionTemplateSettingLocalService =
			(PermissionTemplateSettingLocalService)aopProxy;

		PermissionTemplateSettingLocalServiceUtil.setService(
			permissionTemplateSettingLocalService);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return PermissionTemplateSettingLocalService.class.getName();
	}

	@Override
	public CTPersistence<PermissionTemplateSetting> getCTPersistence() {
		return permissionTemplateSettingPersistence;
	}

	@Override
	public Class<PermissionTemplateSetting> getModelClass() {
		return PermissionTemplateSetting.class;
	}

	@Override
	public <R, E extends Throwable> R updateWithUnsafeFunction(
			UnsafeFunction<CTPersistence<PermissionTemplateSetting>, R, E>
				updateUnsafeFunction)
		throws E {

		return updateUnsafeFunction.apply(permissionTemplateSettingPersistence);
	}

	protected String getModelClassName() {
		return PermissionTemplateSetting.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource =
				permissionTemplateSettingPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	protected PermissionTemplateSettingLocalService
		permissionTemplateSettingLocalService;

	@Reference
	protected PermissionTemplateSettingPersistence
		permissionTemplateSettingPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	private static final Log _log = LogFactoryUtil.getLog(
		PermissionTemplateSettingLocalServiceBaseImpl.class);

}