/**
 * SPDX-FileCopyrightText: (c) 2023 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.portal.kernel.model;

import com.liferay.portal.kernel.model.change.tracking.CTModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the PermissionPropagationEntry service. Represents a row in the &quot;PermissionPropagationEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.portal.model.impl.PermissionPropagationEntryModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.portal.model.impl.PermissionPropagationEntryImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PermissionPropagationEntry
 * @generated
 */
@ProviderType
public interface PermissionPropagationEntryModel
	extends AttachedModel, BaseModel<PermissionPropagationEntry>,
			CTModel<PermissionPropagationEntry>, MVCCModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a permission propagation entry model instance should use the {@link PermissionPropagationEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this permission propagation entry.
	 *
	 * @return the primary key of this permission propagation entry
	 */
	@Override
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this permission propagation entry.
	 *
	 * @param primaryKey the primary key of this permission propagation entry
	 */
	@Override
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mvcc version of this permission propagation entry.
	 *
	 * @return the mvcc version of this permission propagation entry
	 */
	@Override
	public long getMvccVersion();

	/**
	 * Sets the mvcc version of this permission propagation entry.
	 *
	 * @param mvccVersion the mvcc version of this permission propagation entry
	 */
	@Override
	public void setMvccVersion(long mvccVersion);

	/**
	 * Returns the ct collection ID of this permission propagation entry.
	 *
	 * @return the ct collection ID of this permission propagation entry
	 */
	@Override
	public long getCtCollectionId();

	/**
	 * Sets the ct collection ID of this permission propagation entry.
	 *
	 * @param ctCollectionId the ct collection ID of this permission propagation entry
	 */
	@Override
	public void setCtCollectionId(long ctCollectionId);

	/**
	 * Returns the permission propagation entry ID of this permission propagation entry.
	 *
	 * @return the permission propagation entry ID of this permission propagation entry
	 */
	public long getPermissionPropagationEntryId();

	/**
	 * Sets the permission propagation entry ID of this permission propagation entry.
	 *
	 * @param permissionPropagationEntryId the permission propagation entry ID of this permission propagation entry
	 */
	public void setPermissionPropagationEntryId(
		long permissionPropagationEntryId);

	/**
	 * Returns the group ID of this permission propagation entry.
	 *
	 * @return the group ID of this permission propagation entry
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this permission propagation entry.
	 *
	 * @param groupId the group ID of this permission propagation entry
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this permission propagation entry.
	 *
	 * @return the company ID of this permission propagation entry
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this permission propagation entry.
	 *
	 * @param companyId the company ID of this permission propagation entry
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the fully qualified class name of this permission propagation entry.
	 *
	 * @return the fully qualified class name of this permission propagation entry
	 */
	@Override
	public String getClassName();

	public void setClassName(String className);

	/**
	 * Returns the class name ID of this permission propagation entry.
	 *
	 * @return the class name ID of this permission propagation entry
	 */
	@Override
	public long getClassNameId();

	/**
	 * Sets the class name ID of this permission propagation entry.
	 *
	 * @param classNameId the class name ID of this permission propagation entry
	 */
	@Override
	public void setClassNameId(long classNameId);

	/**
	 * Returns the class pk of this permission propagation entry.
	 *
	 * @return the class pk of this permission propagation entry
	 */
	@Override
	public long getClassPK();

	/**
	 * Sets the class pk of this permission propagation entry.
	 *
	 * @param classPK the class pk of this permission propagation entry
	 */
	@Override
	public void setClassPK(long classPK);

	/**
	 * Returns the propagation of this permission propagation entry.
	 *
	 * @return the propagation of this permission propagation entry
	 */
	public boolean getPropagation();

	/**
	 * Returns <code>true</code> if this permission propagation entry is propagation.
	 *
	 * @return <code>true</code> if this permission propagation entry is propagation; <code>false</code> otherwise
	 */
	public boolean isPropagation();

	/**
	 * Sets whether this permission propagation entry is propagation.
	 *
	 * @param propagation the propagation of this permission propagation entry
	 */
	public void setPropagation(boolean propagation);

	@Override
	public PermissionPropagationEntry cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}