/**
 * SPDX-FileCopyrightText: (c) 2023 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.permission.template.model;

import com.liferay.portal.kernel.model.AttachedModel;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.MVCCModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.change.tracking.CTModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the PermissionTemplateSetting service. Represents a row in the &quot;PermissionTemplateSetting&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.permission.template.model.impl.PermissionTemplateSettingModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.permission.template.model.impl.PermissionTemplateSettingImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PermissionTemplateSetting
 * @generated
 */
@ProviderType
public interface PermissionTemplateSettingModel
	extends AttachedModel, BaseModel<PermissionTemplateSetting>,
			CTModel<PermissionTemplateSetting>, MVCCModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a permission template setting model instance should use the {@link PermissionTemplateSetting} interface instead.
	 */

	/**
	 * Returns the primary key of this permission template setting.
	 *
	 * @return the primary key of this permission template setting
	 */
	@Override
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this permission template setting.
	 *
	 * @param primaryKey the primary key of this permission template setting
	 */
	@Override
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mvcc version of this permission template setting.
	 *
	 * @return the mvcc version of this permission template setting
	 */
	@Override
	public long getMvccVersion();

	/**
	 * Sets the mvcc version of this permission template setting.
	 *
	 * @param mvccVersion the mvcc version of this permission template setting
	 */
	@Override
	public void setMvccVersion(long mvccVersion);

	/**
	 * Returns the ct collection ID of this permission template setting.
	 *
	 * @return the ct collection ID of this permission template setting
	 */
	@Override
	public long getCtCollectionId();

	/**
	 * Sets the ct collection ID of this permission template setting.
	 *
	 * @param ctCollectionId the ct collection ID of this permission template setting
	 */
	@Override
	public void setCtCollectionId(long ctCollectionId);

	/**
	 * Returns the permission template setting ID of this permission template setting.
	 *
	 * @return the permission template setting ID of this permission template setting
	 */
	public long getPermissionTemplateSettingId();

	/**
	 * Sets the permission template setting ID of this permission template setting.
	 *
	 * @param permissionTemplateSettingId the permission template setting ID of this permission template setting
	 */
	public void setPermissionTemplateSettingId(
		long permissionTemplateSettingId);

	/**
	 * Returns the group ID of this permission template setting.
	 *
	 * @return the group ID of this permission template setting
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this permission template setting.
	 *
	 * @param groupId the group ID of this permission template setting
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this permission template setting.
	 *
	 * @return the company ID of this permission template setting
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this permission template setting.
	 *
	 * @param companyId the company ID of this permission template setting
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the fully qualified class name of this permission template setting.
	 *
	 * @return the fully qualified class name of this permission template setting
	 */
	@Override
	public String getClassName();

	public void setClassName(String className);

	/**
	 * Returns the class name ID of this permission template setting.
	 *
	 * @return the class name ID of this permission template setting
	 */
	@Override
	public long getClassNameId();

	/**
	 * Sets the class name ID of this permission template setting.
	 *
	 * @param classNameId the class name ID of this permission template setting
	 */
	@Override
	public void setClassNameId(long classNameId);

	/**
	 * Returns the class pk of this permission template setting.
	 *
	 * @return the class pk of this permission template setting
	 */
	@Override
	public long getClassPK();

	/**
	 * Sets the class pk of this permission template setting.
	 *
	 * @param classPK the class pk of this permission template setting
	 */
	@Override
	public void setClassPK(long classPK);

	/**
	 * Returns the permission template enabled of this permission template setting.
	 *
	 * @return the permission template enabled of this permission template setting
	 */
	public boolean getPermissionTemplateEnabled();

	/**
	 * Returns <code>true</code> if this permission template setting is permission template enabled.
	 *
	 * @return <code>true</code> if this permission template setting is permission template enabled; <code>false</code> otherwise
	 */
	public boolean isPermissionTemplateEnabled();

	/**
	 * Sets whether this permission template setting is permission template enabled.
	 *
	 * @param permissionTemplateEnabled the permission template enabled of this permission template setting
	 */
	public void setPermissionTemplateEnabled(boolean permissionTemplateEnabled);

	@Override
	public PermissionTemplateSetting cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}