/**
 * SPDX-FileCopyrightText: (c) 2023 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.portal.service.base;

import com.liferay.petra.function.UnsafeFunction;
import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.model.PermissionPropagationEntry;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PermissionPropagationEntryLocalService;
import com.liferay.portal.kernel.service.PermissionPropagationEntryLocalServiceUtil;
import com.liferay.portal.kernel.service.PersistedModelLocalServiceRegistry;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.service.persistence.PermissionPropagationEntryPersistence;
import com.liferay.portal.kernel.service.persistence.change.tracking.CTPersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the permission propagation entry local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.portal.service.impl.PermissionPropagationEntryLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.liferay.portal.service.impl.PermissionPropagationEntryLocalServiceImpl
 * @generated
 */
public abstract class PermissionPropagationEntryLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements IdentifiableOSGiService, PermissionPropagationEntryLocalService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>PermissionPropagationEntryLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>PermissionPropagationEntryLocalServiceUtil</code>.
	 */

	/**
	 * Adds the permission propagation entry to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect PermissionPropagationEntryLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param permissionPropagationEntry the permission propagation entry
	 * @return the permission propagation entry that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public PermissionPropagationEntry addPermissionPropagationEntry(
		PermissionPropagationEntry permissionPropagationEntry) {

		permissionPropagationEntry.setNew(true);

		return permissionPropagationEntryPersistence.update(
			permissionPropagationEntry);
	}

	/**
	 * Creates a new permission propagation entry with the primary key. Does not add the permission propagation entry to the database.
	 *
	 * @param permissionPropagationEntryId the primary key for the new permission propagation entry
	 * @return the new permission propagation entry
	 */
	@Override
	@Transactional(enabled = false)
	public PermissionPropagationEntry createPermissionPropagationEntry(
		long permissionPropagationEntryId) {

		return permissionPropagationEntryPersistence.create(
			permissionPropagationEntryId);
	}

	/**
	 * Deletes the permission propagation entry with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect PermissionPropagationEntryLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param permissionPropagationEntryId the primary key of the permission propagation entry
	 * @return the permission propagation entry that was removed
	 * @throws PortalException if a permission propagation entry with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public PermissionPropagationEntry deletePermissionPropagationEntry(
			long permissionPropagationEntryId)
		throws PortalException {

		return permissionPropagationEntryPersistence.remove(
			permissionPropagationEntryId);
	}

	/**
	 * Deletes the permission propagation entry from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect PermissionPropagationEntryLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param permissionPropagationEntry the permission propagation entry
	 * @return the permission propagation entry that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public PermissionPropagationEntry deletePermissionPropagationEntry(
		PermissionPropagationEntry permissionPropagationEntry) {

		return permissionPropagationEntryPersistence.remove(
			permissionPropagationEntry);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return permissionPropagationEntryPersistence.dslQuery(dslQuery);
	}

	@Override
	public int dslQueryCount(DSLQuery dslQuery) {
		Long count = dslQuery(dslQuery);

		return count.intValue();
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			PermissionPropagationEntry.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return permissionPropagationEntryPersistence.findWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.portal.model.impl.PermissionPropagationEntryModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return permissionPropagationEntryPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.portal.model.impl.PermissionPropagationEntryModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return permissionPropagationEntryPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return permissionPropagationEntryPersistence.countWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return permissionPropagationEntryPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public PermissionPropagationEntry fetchPermissionPropagationEntry(
		long permissionPropagationEntryId) {

		return permissionPropagationEntryPersistence.fetchByPrimaryKey(
			permissionPropagationEntryId);
	}

	/**
	 * Returns the permission propagation entry with the primary key.
	 *
	 * @param permissionPropagationEntryId the primary key of the permission propagation entry
	 * @return the permission propagation entry
	 * @throws PortalException if a permission propagation entry with the primary key could not be found
	 */
	@Override
	public PermissionPropagationEntry getPermissionPropagationEntry(
			long permissionPropagationEntryId)
		throws PortalException {

		return permissionPropagationEntryPersistence.findByPrimaryKey(
			permissionPropagationEntryId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(
			permissionPropagationEntryLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(PermissionPropagationEntry.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"permissionPropagationEntryId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			permissionPropagationEntryLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(
			PermissionPropagationEntry.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"permissionPropagationEntryId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(
			permissionPropagationEntryLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(PermissionPropagationEntry.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"permissionPropagationEntryId");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return permissionPropagationEntryPersistence.create(
			((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		if (_log.isWarnEnabled()) {
			_log.warn(
				"Implement PermissionPropagationEntryLocalServiceImpl#deletePermissionPropagationEntry(PermissionPropagationEntry) to avoid orphaned data");
		}

		return permissionPropagationEntryLocalService.
			deletePermissionPropagationEntry(
				(PermissionPropagationEntry)persistedModel);
	}

	@Override
	public BasePersistence<PermissionPropagationEntry> getBasePersistence() {
		return permissionPropagationEntryPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return permissionPropagationEntryPersistence.findByPrimaryKey(
			primaryKeyObj);
	}

	/**
	 * Returns a range of all the permission propagation entries.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.portal.model.impl.PermissionPropagationEntryModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of permission propagation entries
	 * @param end the upper bound of the range of permission propagation entries (not inclusive)
	 * @return the range of permission propagation entries
	 */
	@Override
	public List<PermissionPropagationEntry> getPermissionPropagationEntries(
		int start, int end) {

		return permissionPropagationEntryPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of permission propagation entries.
	 *
	 * @return the number of permission propagation entries
	 */
	@Override
	public int getPermissionPropagationEntriesCount() {
		return permissionPropagationEntryPersistence.countAll();
	}

	/**
	 * Updates the permission propagation entry in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect PermissionPropagationEntryLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param permissionPropagationEntry the permission propagation entry
	 * @return the permission propagation entry that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public PermissionPropagationEntry updatePermissionPropagationEntry(
		PermissionPropagationEntry permissionPropagationEntry) {

		return permissionPropagationEntryPersistence.update(
			permissionPropagationEntry);
	}

	/**
	 * Returns the permission propagation entry local service.
	 *
	 * @return the permission propagation entry local service
	 */
	public PermissionPropagationEntryLocalService
		getPermissionPropagationEntryLocalService() {

		return permissionPropagationEntryLocalService;
	}

	/**
	 * Sets the permission propagation entry local service.
	 *
	 * @param permissionPropagationEntryLocalService the permission propagation entry local service
	 */
	public void setPermissionPropagationEntryLocalService(
		PermissionPropagationEntryLocalService
			permissionPropagationEntryLocalService) {

		this.permissionPropagationEntryLocalService =
			permissionPropagationEntryLocalService;
	}

	/**
	 * Returns the permission propagation entry persistence.
	 *
	 * @return the permission propagation entry persistence
	 */
	public PermissionPropagationEntryPersistence
		getPermissionPropagationEntryPersistence() {

		return permissionPropagationEntryPersistence;
	}

	/**
	 * Sets the permission propagation entry persistence.
	 *
	 * @param permissionPropagationEntryPersistence the permission propagation entry persistence
	 */
	public void setPermissionPropagationEntryPersistence(
		PermissionPropagationEntryPersistence
			permissionPropagationEntryPersistence) {

		this.permissionPropagationEntryPersistence =
			permissionPropagationEntryPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService
		getCounterLocalService() {

		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService
			counterLocalService) {

		this.counterLocalService = counterLocalService;
	}

	public void afterPropertiesSet() {
		persistedModelLocalServiceRegistry.register(
			"com.liferay.portal.kernel.model.PermissionPropagationEntry",
			permissionPropagationEntryLocalService);

		PermissionPropagationEntryLocalServiceUtil.setService(
			permissionPropagationEntryLocalService);
	}

	public void destroy() {
		persistedModelLocalServiceRegistry.unregister(
			"com.liferay.portal.kernel.model.PermissionPropagationEntry");

		PermissionPropagationEntryLocalServiceUtil.setService(null);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return PermissionPropagationEntryLocalService.class.getName();
	}

	@Override
	public CTPersistence<PermissionPropagationEntry> getCTPersistence() {
		return permissionPropagationEntryPersistence;
	}

	@Override
	public Class<PermissionPropagationEntry> getModelClass() {
		return PermissionPropagationEntry.class;
	}

	@Override
	public <R, E extends Throwable> R updateWithUnsafeFunction(
			UnsafeFunction<CTPersistence<PermissionPropagationEntry>, R, E>
				updateUnsafeFunction)
		throws E {

		return updateUnsafeFunction.apply(
			permissionPropagationEntryPersistence);
	}

	protected String getModelClassName() {
		return PermissionPropagationEntry.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource =
				permissionPropagationEntryPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	@BeanReference(type = PermissionPropagationEntryLocalService.class)
	protected PermissionPropagationEntryLocalService
		permissionPropagationEntryLocalService;

	@BeanReference(type = PermissionPropagationEntryPersistence.class)
	protected PermissionPropagationEntryPersistence
		permissionPropagationEntryPersistence;

	@BeanReference(
		type = com.liferay.counter.kernel.service.CounterLocalService.class
	)
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	private static final Log _log = LogFactoryUtil.getLog(
		PermissionPropagationEntryLocalServiceBaseImpl.class);

	@BeanReference(type = PersistedModelLocalServiceRegistry.class)
	protected PersistedModelLocalServiceRegistry
		persistedModelLocalServiceRegistry;

}