/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.portal.service.base;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.model.PermissionPropagationEntry;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.service.BaseServiceImpl;
import com.liferay.portal.kernel.service.PermissionPropagationEntryService;
import com.liferay.portal.kernel.service.PermissionPropagationEntryServiceUtil;
import com.liferay.portal.kernel.service.persistence.PermissionPropagationEntryPersistence;
import com.liferay.portal.kernel.util.PortalUtil;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the permission propagation entry remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.portal.service.impl.PermissionPropagationEntryServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.liferay.portal.service.impl.PermissionPropagationEntryServiceImpl
 * @generated
 */
public abstract class PermissionPropagationEntryServiceBaseImpl
	extends BaseServiceImpl
	implements IdentifiableOSGiService, PermissionPropagationEntryService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>PermissionPropagationEntryService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>PermissionPropagationEntryServiceUtil</code>.
	 */

	/**
	 * Returns the permission propagation entry local service.
	 *
	 * @return the permission propagation entry local service
	 */
	public
		com.liferay.portal.kernel.service.PermissionPropagationEntryLocalService
			getPermissionPropagationEntryLocalService() {

		return permissionPropagationEntryLocalService;
	}

	/**
	 * Sets the permission propagation entry local service.
	 *
	 * @param permissionPropagationEntryLocalService the permission propagation entry local service
	 */
	public void setPermissionPropagationEntryLocalService(
		com.liferay.portal.kernel.service.PermissionPropagationEntryLocalService
			permissionPropagationEntryLocalService) {

		this.permissionPropagationEntryLocalService =
			permissionPropagationEntryLocalService;
	}

	/**
	 * Returns the permission propagation entry remote service.
	 *
	 * @return the permission propagation entry remote service
	 */
	public PermissionPropagationEntryService
		getPermissionPropagationEntryService() {

		return permissionPropagationEntryService;
	}

	/**
	 * Sets the permission propagation entry remote service.
	 *
	 * @param permissionPropagationEntryService the permission propagation entry remote service
	 */
	public void setPermissionPropagationEntryService(
		PermissionPropagationEntryService permissionPropagationEntryService) {

		this.permissionPropagationEntryService =
			permissionPropagationEntryService;
	}

	/**
	 * Returns the permission propagation entry persistence.
	 *
	 * @return the permission propagation entry persistence
	 */
	public PermissionPropagationEntryPersistence
		getPermissionPropagationEntryPersistence() {

		return permissionPropagationEntryPersistence;
	}

	/**
	 * Sets the permission propagation entry persistence.
	 *
	 * @param permissionPropagationEntryPersistence the permission propagation entry persistence
	 */
	public void setPermissionPropagationEntryPersistence(
		PermissionPropagationEntryPersistence
			permissionPropagationEntryPersistence) {

		this.permissionPropagationEntryPersistence =
			permissionPropagationEntryPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService
		getCounterLocalService() {

		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService
			counterLocalService) {

		this.counterLocalService = counterLocalService;
	}

	public void afterPropertiesSet() {
		PermissionPropagationEntryServiceUtil.setService(
			permissionPropagationEntryService);
	}

	public void destroy() {
		PermissionPropagationEntryServiceUtil.setService(null);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return PermissionPropagationEntryService.class.getName();
	}

	protected Class<?> getModelClass() {
		return PermissionPropagationEntry.class;
	}

	protected String getModelClassName() {
		return PermissionPropagationEntry.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource =
				permissionPropagationEntryPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	@BeanReference(
		type = com.liferay.portal.kernel.service.PermissionPropagationEntryLocalService.class
	)
	protected
		com.liferay.portal.kernel.service.PermissionPropagationEntryLocalService
			permissionPropagationEntryLocalService;

	@BeanReference(type = PermissionPropagationEntryService.class)
	protected PermissionPropagationEntryService
		permissionPropagationEntryService;

	@BeanReference(type = PermissionPropagationEntryPersistence.class)
	protected PermissionPropagationEntryPersistence
		permissionPropagationEntryPersistence;

	@BeanReference(
		type = com.liferay.counter.kernel.service.CounterLocalService.class
	)
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	private static final Log _log = LogFactoryUtil.getLog(
		PermissionPropagationEntryServiceBaseImpl.class);

}